// Package artifact implements the ArtifactGenerator port.
// It renders a hardened, multi-stage Dockerfile from a template embedded into
// the binary at compile time, and ensures a .dockerignore exists at the
// project root.
package artifact

import (
	"context"
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/francisco3ferraz/vessel-cli/pkg/types"
)

//go:embed templates/dockerfile.tmpl
var templateFS embed.FS

// Generator implements ports.ArtifactGenerator.
type Generator struct{}

// NewGenerator returns a new Generator.
func NewGenerator() *Generator { return &Generator{} }

// GenerateDockerfile renders the Dockerfile template into .vessel-cli/Dockerfile
// and writes a .dockerignore at the project root if one does not already exist.
//
// The Dockerfile is placed inside .vessel-cli/ (which is gitignored) so it
// does not pollute the project root. Docker build is called with the project
// root as the build context and -f .vessel-cli/Dockerfile.
//
// Idempotent: re-running always produces the same output for the same inputs.
func (g *Generator) GenerateDockerfile(_ context.Context, pctx *types.PipelineContext) error {
	spec := DockerfileSpec{
		GoVersion:   pctx.GoVersion,
		BinaryName:  pctx.BinaryName,
		BuildTarget: detectBuildTarget(pctx.ProjectDir, pctx.BinaryName),
		Port:        8080,
	}

	tmpl, err := template.ParseFS(templateFS, "templates/dockerfile.tmpl")
	if err != nil {
		return fmt.Errorf("parse Dockerfile template: %w", err)
	}

	// Dockerfile lives in the managed workspace, not the project root.
	dockerfilePath := filepath.Join(pctx.ProjectDir, ".vessel-cli", "Dockerfile")
	f, err := os.Create(dockerfilePath)
	if err != nil {
		return fmt.Errorf("create Dockerfile at %s: %w", dockerfilePath, err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, spec); err != nil {
		return fmt.Errorf("render Dockerfile: %w", err)
	}

	pctx.DockerfilePath = dockerfilePath

	// .dockerignore at the project root (never overwrite if already present).
	if err := ensureDockerignore(pctx.ProjectDir); err != nil {
		// Non-fatal: log but do not abort the pipeline.
		fmt.Fprintf(os.Stderr, "warning: could not write .dockerignore: %v\n", err)
	}

	return nil
}

// detectBuildTarget returns the go build argument that produces a single binary.
//
//	cmd/<binaryName>/ exists → "./cmd/<binaryName>"   (most specific)
//	cmd/ exists with entries → "./cmd/..."             (multi-binary layout)
//	otherwise               → "."                     (main.go at root)
func detectBuildTarget(projectDir, binaryName string) string {
	specificCmd := filepath.Join(projectDir, "cmd", binaryName)
	if stat, err := os.Stat(specificCmd); err == nil && stat.IsDir() {
		return "./cmd/" + binaryName
	}

	cmdDir := filepath.Join(projectDir, "cmd")
	if entries, err := os.ReadDir(cmdDir); err == nil && len(entries) > 0 {
		return "./cmd/..."
	}

	return "."
}

// ensureDockerignore writes a minimal .dockerignore at projectDir if one does
// not already exist. Never overwrites — if the user has their own, we leave it.
func ensureDockerignore(projectDir string) error {
	diPath := filepath.Join(projectDir, ".dockerignore")
	if _, err := os.Stat(diPath); err == nil {
		return nil // already exists, do not touch it
	}

	const content = "# Generated by vessel-cli — edit to add project-specific exclusions\n" +
		".vessel-cli/\n" +
		".git/\n" +
		"*.md\n"

	return os.WriteFile(diPath, []byte(content), 0644)
}

// dockerignoreHasEntry reports whether the .dockerignore at projectDir already
// contains the given entry. Used in tests.
func dockerignoreHasEntry(projectDir, entry string) bool {
	data, err := os.ReadFile(filepath.Join(projectDir, ".dockerignore"))
	if err != nil {
		return false
	}
	return strings.Contains(string(data), entry)
}
